/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminProfile {
  'id' : string,
  'adminKey' : string,
  'name' : string,
  'role' : UserRole,
  'adminPassword' : string,
}
export interface Booking {
  'id' : string,
  'customerName' : string,
  'status' : BookingStatus,
  'userId' : string,
  'hotelId' : string,
  'checkInDate' : Time,
  'guestInfo' : GuestProfile,
  'bookingDate' : Time,
  'checkOutDate' : Time,
  'roomId' : string,
  'totalPrice' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'confirmed' : null } |
  { 'pendingConfirmation' : null };
export type ExternalBlob = Uint8Array;
export interface GuestProfile {
  'id' : string,
  'contact' : string,
  'name' : string,
  'bookingHistory' : Array<string>,
}
export interface HomeStay {
  'id' : string,
  'photoUrls' : Array<string>,
  'ownerMessage' : string,
  'ownerType' : { 'admin' : null } |
    { 'partner' : null },
  'partnerName' : string,
  'hotelId' : string,
  'ratings' : Array<bigint>,
  'description' : string,
  'amenities' : Array<string>,
  'googleMapsLink' : [] | [string],
  'videoUrls' : Array<string>,
  'partnerId' : [] | [string],
  'availability' : boolean,
  'price' : bigint,
  'roomType' : RoomType,
  'distanceFromTemple' : [] | [bigint],
  'photos' : Array<ExternalBlob>,
  'partnerPhoneNumber' : string,
}
export interface Hotel {
  'id' : string,
  'name' : string,
  'description' : string,
  'amenities' : Array<string>,
  'address' : string,
  'photos' : Array<ExternalBlob>,
}
export interface Notification {
  'id' : string,
  'notificationType' : { 'profileUpdate' : null } |
    { 'booking' : null } |
    { 'newLogin' : null } |
    { 'partner' : null } |
    { 'payment' : null },
  'unread' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export interface PartnerProfile {
  'id' : string,
  'contact' : string,
  'name' : string,
  'registrationDate' : Time,
  'rooms' : Array<string>,
}
export interface PartnerRoomUpdate {
  'availability' : boolean,
  'roomId' : string,
  'price' : bigint,
}
export interface RoomPasscodeConfig { 'passcode' : string, 'roomId' : string }
export type RoomType = { 'double' : null } |
  { 'suite' : null } |
  { 'single' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addHomeStayWithOptionalPasscode' : ActorMethod<
    [HomeStay, [] | [string]],
    undefined
  >,
  'addHotel' : ActorMethod<[Hotel], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateAdmin' : ActorMethod<[string, string], boolean>,
  'authenticatePartnerWithPasscode' : ActorMethod<[string], string>,
  'cancelBooking' : ActorMethod<[string], undefined>,
  'checkAdminAuthentication' : ActorMethod<[], boolean>,
  'checkPartnerAuthentication' : ActorMethod<[], boolean>,
  'confirmBookingPayment' : ActorMethod<[string], undefined>,
  'createBooking' : ActorMethod<[Booking], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGuestProfile' : ActorMethod<[GuestProfile], undefined>,
  'deleteHomeStay' : ActorMethod<[string], undefined>,
  'deleteHotel' : ActorMethod<[string], undefined>,
  'deleteNotification' : ActorMethod<[string], undefined>,
  'deletePartnerProfile' : ActorMethod<[string], undefined>,
  'getAdminDashboardData' : ActorMethod<
    [],
    [AdminProfile, Array<Hotel>, Array<HomeStay>, Array<Booking>]
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllPartnerProfiles' : ActorMethod<[], Array<PartnerProfile>>,
  'getAllRoomPasscodes' : ActorMethod<[], Array<RoomPasscodeConfig>>,
  'getAvailableHomeStays' : ActorMethod<[], Array<HomeStay>>,
  'getAvailableHotels' : ActorMethod<[], Array<Hotel>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGuestProfile' : ActorMethod<[string], [] | [GuestProfile]>,
  'getHomeStayAmenities' : ActorMethod<[string], Array<string>>,
  'getHomeStayDetails' : ActorMethod<[string], [] | [HomeStay]>,
  'getHotelAmenities' : ActorMethod<[string], Array<string>>,
  'getHotels' : ActorMethod<[], Array<Hotel>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPartnerAuthenticatedRoomId' : ActorMethod<[], [] | [string]>,
  'getPartnerNotifications' : ActorMethod<[string], Array<Notification>>,
  'getPartnerProfile' : ActorMethod<[string], [] | [PartnerProfile]>,
  'getPartnerRooms' : ActorMethod<[string], Array<HomeStay>>,
  'getRoomPasscode' : ActorMethod<[string], [] | [string]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUnreadNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasCustomerLoggedInBefore' : ActorMethod<[], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'logoutAdmin' : ActorMethod<[], undefined>,
  'logoutPartner' : ActorMethod<[], undefined>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'recordCustomerFirstLogin' : ActorMethod<[string], boolean>,
  'registerPartnerProfile' : ActorMethod<[PartnerProfile], undefined>,
  'removeRoomPasscode' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRoomPasscode' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminCredentials' : ActorMethod<[string, string], undefined>,
  'updateBooking' : ActorMethod<[Booking], undefined>,
  'updateGuestProfile' : ActorMethod<[GuestProfile], undefined>,
  'updateHomeStay' : ActorMethod<[HomeStay], undefined>,
  'updateHotel' : ActorMethod<[Hotel], undefined>,
  'updatePartnerProfile' : ActorMethod<[PartnerProfile], undefined>,
  'updatePartnerRoomDetails' : ActorMethod<[PartnerRoomUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];