/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RoomType = IDL.Variant({
  'double' : IDL.Null,
  'suite' : IDL.Null,
  'single' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const HomeStay = IDL.Record({
  'id' : IDL.Text,
  'photoUrls' : IDL.Vec(IDL.Text),
  'ownerMessage' : IDL.Text,
  'ownerType' : IDL.Variant({ 'admin' : IDL.Null, 'partner' : IDL.Null }),
  'partnerName' : IDL.Text,
  'hotelId' : IDL.Text,
  'ratings' : IDL.Vec(IDL.Nat),
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'googleMapsLink' : IDL.Opt(IDL.Text),
  'videoUrls' : IDL.Vec(IDL.Text),
  'partnerId' : IDL.Opt(IDL.Text),
  'availability' : IDL.Bool,
  'price' : IDL.Nat,
  'roomType' : RoomType,
  'distanceFromTemple' : IDL.Opt(IDL.Nat),
  'photos' : IDL.Vec(ExternalBlob),
  'partnerPhoneNumber' : IDL.Text,
});
export const Hotel = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'confirmed' : IDL.Null,
  'pendingConfirmation' : IDL.Null,
});
export const Time = IDL.Int;
export const GuestProfile = IDL.Record({
  'id' : IDL.Text,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'bookingHistory' : IDL.Vec(IDL.Text),
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'userId' : IDL.Text,
  'hotelId' : IDL.Text,
  'checkInDate' : Time,
  'guestInfo' : GuestProfile,
  'bookingDate' : Time,
  'checkOutDate' : Time,
  'roomId' : IDL.Text,
  'totalPrice' : IDL.Nat,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AdminProfile = IDL.Record({
  'id' : IDL.Text,
  'adminKey' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'adminPassword' : IDL.Text,
});
export const PartnerProfile = IDL.Record({
  'id' : IDL.Text,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'registrationDate' : Time,
  'rooms' : IDL.Vec(IDL.Text),
});
export const RoomPasscodeConfig = IDL.Record({
  'passcode' : IDL.Text,
  'roomId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'notificationType' : IDL.Variant({
    'profileUpdate' : IDL.Null,
    'booking' : IDL.Null,
    'newLogin' : IDL.Null,
    'partner' : IDL.Null,
    'payment' : IDL.Null,
  }),
  'unread' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const PartnerRoomUpdate = IDL.Record({
  'availability' : IDL.Bool,
  'roomId' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addHomeStayWithOptionalPasscode' : IDL.Func(
      [HomeStay, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'addHotel' : IDL.Func([Hotel], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'authenticatePartnerWithPasscode' : IDL.Func([IDL.Text], [IDL.Text], []),
  'cancelBooking' : IDL.Func([IDL.Text], [], []),
  'checkAdminAuthentication' : IDL.Func([], [IDL.Bool], ['query']),
  'checkPartnerAuthentication' : IDL.Func([], [IDL.Bool], ['query']),
  'confirmBookingPayment' : IDL.Func([IDL.Text], [], []),
  'createBooking' : IDL.Func([Booking], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGuestProfile' : IDL.Func([GuestProfile], [], []),
  'deleteHomeStay' : IDL.Func([IDL.Text], [], []),
  'deleteHotel' : IDL.Func([IDL.Text], [], []),
  'deleteNotification' : IDL.Func([IDL.Text], [], []),
  'deletePartnerProfile' : IDL.Func([IDL.Text], [], []),
  'getAdminDashboardData' : IDL.Func(
      [],
      [AdminProfile, IDL.Vec(Hotel), IDL.Vec(HomeStay), IDL.Vec(Booking)],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllPartnerProfiles' : IDL.Func([], [IDL.Vec(PartnerProfile)], ['query']),
  'getAllRoomPasscodes' : IDL.Func(
      [],
      [IDL.Vec(RoomPasscodeConfig)],
      ['query'],
    ),
  'getAvailableHomeStays' : IDL.Func([], [IDL.Vec(HomeStay)], ['query']),
  'getAvailableHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGuestProfile' : IDL.Func([IDL.Text], [IDL.Opt(GuestProfile)], ['query']),
  'getHomeStayAmenities' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getHomeStayDetails' : IDL.Func([IDL.Text], [IDL.Opt(HomeStay)], ['query']),
  'getHotelAmenities' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPartnerAuthenticatedRoomId' : IDL.Func(
      [],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getPartnerNotifications' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getPartnerProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PartnerProfile)],
      ['query'],
    ),
  'getPartnerRooms' : IDL.Func([IDL.Text], [IDL.Vec(HomeStay)], ['query']),
  'getRoomPasscode' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUnreadNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasCustomerLoggedInBefore' : IDL.Func([], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'logoutAdmin' : IDL.Func([], [], []),
  'logoutPartner' : IDL.Func([], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
  'recordCustomerFirstLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'registerPartnerProfile' : IDL.Func([PartnerProfile], [], []),
  'removeRoomPasscode' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRoomPasscode' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateBooking' : IDL.Func([Booking], [], []),
  'updateGuestProfile' : IDL.Func([GuestProfile], [], []),
  'updateHomeStay' : IDL.Func([HomeStay], [], []),
  'updateHotel' : IDL.Func([Hotel], [], []),
  'updatePartnerProfile' : IDL.Func([PartnerProfile], [], []),
  'updatePartnerRoomDetails' : IDL.Func([PartnerRoomUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RoomType = IDL.Variant({
    'double' : IDL.Null,
    'suite' : IDL.Null,
    'single' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const HomeStay = IDL.Record({
    'id' : IDL.Text,
    'photoUrls' : IDL.Vec(IDL.Text),
    'ownerMessage' : IDL.Text,
    'ownerType' : IDL.Variant({ 'admin' : IDL.Null, 'partner' : IDL.Null }),
    'partnerName' : IDL.Text,
    'hotelId' : IDL.Text,
    'ratings' : IDL.Vec(IDL.Nat),
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'googleMapsLink' : IDL.Opt(IDL.Text),
    'videoUrls' : IDL.Vec(IDL.Text),
    'partnerId' : IDL.Opt(IDL.Text),
    'availability' : IDL.Bool,
    'price' : IDL.Nat,
    'roomType' : RoomType,
    'distanceFromTemple' : IDL.Opt(IDL.Nat),
    'photos' : IDL.Vec(ExternalBlob),
    'partnerPhoneNumber' : IDL.Text,
  });
  const Hotel = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'confirmed' : IDL.Null,
    'pendingConfirmation' : IDL.Null,
  });
  const Time = IDL.Int;
  const GuestProfile = IDL.Record({
    'id' : IDL.Text,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'bookingHistory' : IDL.Vec(IDL.Text),
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'userId' : IDL.Text,
    'hotelId' : IDL.Text,
    'checkInDate' : Time,
    'guestInfo' : GuestProfile,
    'bookingDate' : Time,
    'checkOutDate' : Time,
    'roomId' : IDL.Text,
    'totalPrice' : IDL.Nat,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AdminProfile = IDL.Record({
    'id' : IDL.Text,
    'adminKey' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'adminPassword' : IDL.Text,
  });
  const PartnerProfile = IDL.Record({
    'id' : IDL.Text,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'registrationDate' : Time,
    'rooms' : IDL.Vec(IDL.Text),
  });
  const RoomPasscodeConfig = IDL.Record({
    'passcode' : IDL.Text,
    'roomId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'notificationType' : IDL.Variant({
      'profileUpdate' : IDL.Null,
      'booking' : IDL.Null,
      'newLogin' : IDL.Null,
      'partner' : IDL.Null,
      'payment' : IDL.Null,
    }),
    'unread' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const PartnerRoomUpdate = IDL.Record({
    'availability' : IDL.Bool,
    'roomId' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addHomeStayWithOptionalPasscode' : IDL.Func(
        [HomeStay, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addHotel' : IDL.Func([Hotel], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'authenticatePartnerWithPasscode' : IDL.Func([IDL.Text], [IDL.Text], []),
    'cancelBooking' : IDL.Func([IDL.Text], [], []),
    'checkAdminAuthentication' : IDL.Func([], [IDL.Bool], ['query']),
    'checkPartnerAuthentication' : IDL.Func([], [IDL.Bool], ['query']),
    'confirmBookingPayment' : IDL.Func([IDL.Text], [], []),
    'createBooking' : IDL.Func([Booking], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGuestProfile' : IDL.Func([GuestProfile], [], []),
    'deleteHomeStay' : IDL.Func([IDL.Text], [], []),
    'deleteHotel' : IDL.Func([IDL.Text], [], []),
    'deleteNotification' : IDL.Func([IDL.Text], [], []),
    'deletePartnerProfile' : IDL.Func([IDL.Text], [], []),
    'getAdminDashboardData' : IDL.Func(
        [],
        [AdminProfile, IDL.Vec(Hotel), IDL.Vec(HomeStay), IDL.Vec(Booking)],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllPartnerProfiles' : IDL.Func(
        [],
        [IDL.Vec(PartnerProfile)],
        ['query'],
      ),
    'getAllRoomPasscodes' : IDL.Func(
        [],
        [IDL.Vec(RoomPasscodeConfig)],
        ['query'],
      ),
    'getAvailableHomeStays' : IDL.Func([], [IDL.Vec(HomeStay)], ['query']),
    'getAvailableHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGuestProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuestProfile)],
        ['query'],
      ),
    'getHomeStayAmenities' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getHomeStayDetails' : IDL.Func([IDL.Text], [IDL.Opt(HomeStay)], ['query']),
    'getHotelAmenities' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPartnerAuthenticatedRoomId' : IDL.Func(
        [],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getPartnerNotifications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPartnerProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PartnerProfile)],
        ['query'],
      ),
    'getPartnerRooms' : IDL.Func([IDL.Text], [IDL.Vec(HomeStay)], ['query']),
    'getRoomPasscode' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUnreadNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasCustomerLoggedInBefore' : IDL.Func([], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'logoutAdmin' : IDL.Func([], [], []),
    'logoutPartner' : IDL.Func([], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
    'recordCustomerFirstLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'registerPartnerProfile' : IDL.Func([PartnerProfile], [], []),
    'removeRoomPasscode' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRoomPasscode' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateBooking' : IDL.Func([Booking], [], []),
    'updateGuestProfile' : IDL.Func([GuestProfile], [], []),
    'updateHomeStay' : IDL.Func([HomeStay], [], []),
    'updateHotel' : IDL.Func([Hotel], [], []),
    'updatePartnerProfile' : IDL.Func([PartnerProfile], [], []),
    'updatePartnerRoomDetails' : IDL.Func([PartnerRoomUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };