/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RoomPasscodeConfig {
    passcode: string;
    roomId: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PartnerRoomUpdate {
    availability: boolean;
    roomId: string;
    price: bigint;
}
export interface HomeStay {
    id: string;
    photoUrls: Array<string>;
    ownerMessage: string;
    ownerType: Variant_admin_partner;
    partnerName: string;
    hotelId: string;
    ratings: Array<bigint>;
    description: string;
    amenities: Array<string>;
    googleMapsLink?: string;
    videoUrls: Array<string>;
    partnerId?: string;
    availability: boolean;
    price: bigint;
    roomType: RoomType;
    distanceFromTemple?: bigint;
    photos: Array<ExternalBlob>;
    partnerPhoneNumber: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AdminProfile {
    id: string;
    adminKey: string;
    name: string;
    role: UserRole;
    adminPassword: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Hotel {
    id: string;
    name: string;
    description: string;
    amenities: Array<string>;
    address: string;
    photos: Array<ExternalBlob>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Notification {
    id: string;
    notificationType: Variant_profileUpdate_booking_newLogin_partner_payment;
    unread: boolean;
    message: string;
    timestamp: Time;
}
export interface GuestProfile {
    id: string;
    contact: string;
    name: string;
    bookingHistory: Array<string>;
}
export interface PartnerProfile {
    id: string;
    contact: string;
    name: string;
    registrationDate: Time;
    rooms: Array<string>;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Booking {
    id: string;
    customerName: string;
    status: BookingStatus;
    userId: string;
    hotelId: string;
    checkInDate: Time;
    guestInfo: GuestProfile;
    bookingDate: Time;
    checkOutDate: Time;
    roomId: string;
    totalPrice: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    confirmed = "confirmed",
    pendingConfirmation = "pendingConfirmation"
}
export enum RoomType {
    double_ = "double",
    suite = "suite",
    single = "single"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_admin_partner {
    admin = "admin",
    partner = "partner"
}
export enum Variant_profileUpdate_booking_newLogin_partner_payment {
    profileUpdate = "profileUpdate",
    booking = "booking",
    newLogin = "newLogin",
    partner = "partner",
    payment = "payment"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addHomeStayWithOptionalPasscode(homeStay: HomeStay, passcode: string | null): Promise<void>;
    addHotel(hotel: Hotel): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authenticateAdmin(key: string, password: string): Promise<boolean>;
    authenticatePartnerWithPasscode(passcode: string): Promise<string>;
    cancelBooking(bookingId: string): Promise<void>;
    checkAdminAuthentication(): Promise<boolean>;
    checkPartnerAuthentication(): Promise<boolean>;
    confirmBookingPayment(bookingId: string): Promise<void>;
    createBooking(booking: Booking): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createGuestProfile(profile: GuestProfile): Promise<void>;
    deleteHomeStay(homestayId: string): Promise<void>;
    deleteHotel(hotelId: string): Promise<void>;
    deleteNotification(notificationId: string): Promise<void>;
    deletePartnerProfile(partnerId: string): Promise<void>;
    getAdminDashboardData(): Promise<[AdminProfile, Array<Hotel>, Array<HomeStay>, Array<Booking>]>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllPartnerProfiles(): Promise<Array<PartnerProfile>>;
    getAllRoomPasscodes(): Promise<Array<RoomPasscodeConfig>>;
    getAvailableHomeStays(): Promise<Array<HomeStay>>;
    getAvailableHotels(): Promise<Array<Hotel>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGuestProfile(guestId: string): Promise<GuestProfile | null>;
    getHomeStayAmenities(homestayId: string): Promise<Array<string>>;
    getHomeStayDetails(homeStayId: string): Promise<HomeStay | null>;
    getHotelAmenities(hotelId: string): Promise<Array<string>>;
    getHotels(): Promise<Array<Hotel>>;
    getMyBookings(): Promise<Array<Booking>>;
    getNotifications(): Promise<Array<Notification>>;
    getPartnerAuthenticatedRoomId(): Promise<string | null>;
    getPartnerNotifications(partnerId: string): Promise<Array<Notification>>;
    getPartnerProfile(partnerId: string): Promise<PartnerProfile | null>;
    getPartnerRooms(partnerId: string): Promise<Array<HomeStay>>;
    getRoomPasscode(roomId: string): Promise<string | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUnreadNotifications(): Promise<Array<Notification>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasCustomerLoggedInBefore(): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    logoutAdmin(): Promise<void>;
    logoutPartner(): Promise<void>;
    markNotificationAsRead(notificationId: string): Promise<void>;
    recordCustomerFirstLogin(customerName: string): Promise<boolean>;
    registerPartnerProfile(profile: PartnerProfile): Promise<void>;
    removeRoomPasscode(passcode: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setRoomPasscode(roomId: string, passcode: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAdminCredentials(newKey: string, newPassword: string): Promise<void>;
    updateBooking(booking: Booking): Promise<void>;
    updateGuestProfile(profile: GuestProfile): Promise<void>;
    updateHomeStay(homestay: HomeStay): Promise<void>;
    updateHotel(hotel: Hotel): Promise<void>;
    updatePartnerProfile(profile: PartnerProfile): Promise<void>;
    updatePartnerRoomDetails(update: PartnerRoomUpdate): Promise<void>;
}
import type { AdminProfile as _AdminProfile, Booking as _Booking, BookingStatus as _BookingStatus, ExternalBlob as _ExternalBlob, GuestProfile as _GuestProfile, HomeStay as _HomeStay, Hotel as _Hotel, Notification as _Notification, PartnerProfile as _PartnerProfile, RoomType as _RoomType, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addHomeStayWithOptionalPasscode(arg0: HomeStay, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHomeStayWithOptionalPasscode(await to_candid_HomeStay_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHomeStayWithOptionalPasscode(await to_candid_HomeStay_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addHotel(arg0: Hotel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHotel(await to_candid_Hotel_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHotel(await to_candid_Hotel_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticateAdmin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateAdmin(arg0, arg1);
            return result;
        }
    }
    async authenticatePartnerWithPasscode(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticatePartnerWithPasscode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticatePartnerWithPasscode(arg0);
            return result;
        }
    }
    async cancelBooking(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async checkAdminAuthentication(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAdminAuthentication();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAdminAuthentication();
            return result;
        }
    }
    async checkPartnerAuthentication(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkPartnerAuthentication();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkPartnerAuthentication();
            return result;
        }
    }
    async confirmBookingPayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBookingPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBookingPayment(arg0);
            return result;
        }
    }
    async createBooking(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_Booking_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_Booking_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createGuestProfile(arg0: GuestProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGuestProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGuestProfile(arg0);
            return result;
        }
    }
    async deleteHomeStay(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHomeStay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHomeStay(arg0);
            return result;
        }
    }
    async deleteHotel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHotel(arg0);
            return result;
        }
    }
    async deleteNotification(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotification(arg0);
            return result;
        }
    }
    async deletePartnerProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePartnerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePartnerProfile(arg0);
            return result;
        }
    }
    async getAdminDashboardData(): Promise<[AdminProfile, Array<Hotel>, Array<HomeStay>, Array<Booking>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardData();
                return [
                    from_candid_AdminProfile_n24(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_vec_n28(this._uploadFile, this._downloadFile, result[1]),
                    from_candid_vec_n33(this._uploadFile, this._downloadFile, result[2]),
                    from_candid_vec_n40(this._uploadFile, this._downloadFile, result[3])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardData();
            return [
                from_candid_AdminProfile_n24(this._uploadFile, this._downloadFile, result[0]),
                from_candid_vec_n28(this._uploadFile, this._downloadFile, result[1]),
                from_candid_vec_n33(this._uploadFile, this._downloadFile, result[2]),
                from_candid_vec_n40(this._uploadFile, this._downloadFile, result[3])
            ];
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPartnerProfiles(): Promise<Array<PartnerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPartnerProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPartnerProfiles();
            return result;
        }
    }
    async getAllRoomPasscodes(): Promise<Array<RoomPasscodeConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRoomPasscodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRoomPasscodes();
            return result;
        }
    }
    async getAvailableHomeStays(): Promise<Array<HomeStay>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableHomeStays();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableHomeStays();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableHotels(): Promise<Array<Hotel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableHotels();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableHotels();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuestProfile(arg0: string): Promise<GuestProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuestProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuestProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomeStayAmenities(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeStayAmenities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeStayAmenities(arg0);
            return result;
        }
    }
    async getHomeStayDetails(arg0: string): Promise<HomeStay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeStayDetails(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeStayDetails(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotelAmenities(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelAmenities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelAmenities(arg0);
            return result;
        }
    }
    async getHotels(): Promise<Array<Hotel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotels();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotels();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerAuthenticatedRoomId(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerAuthenticatedRoomId();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerAuthenticatedRoomId();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerNotifications(arg0: string): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerNotifications(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerNotifications(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerProfile(arg0: string): Promise<PartnerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerProfile(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerProfile(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerRooms(arg0: string): Promise<Array<HomeStay>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerRooms(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerRooms(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomPasscode(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomPasscode(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomPasscode(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotifications();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotifications();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasCustomerLoggedInBefore(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasCustomerLoggedInBefore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasCustomerLoggedInBefore();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async logoutAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutAdmin();
            return result;
        }
    }
    async logoutPartner(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutPartner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutPartner();
            return result;
        }
    }
    async markNotificationAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async recordCustomerFirstLogin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.recordCustomerFirstLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordCustomerFirstLogin(arg0);
            return result;
        }
    }
    async registerPartnerProfile(arg0: PartnerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPartnerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPartnerProfile(arg0);
            return result;
        }
    }
    async removeRoomPasscode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRoomPasscode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRoomPasscode(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setRoomPasscode(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRoomPasscode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRoomPasscode(arg0, arg1);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAdminCredentials(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminCredentials(arg0, arg1);
            return result;
        }
    }
    async updateBooking(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(to_candid_Booking_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(to_candid_Booking_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateGuestProfile(arg0: GuestProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGuestProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGuestProfile(arg0);
            return result;
        }
    }
    async updateHomeStay(arg0: HomeStay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomeStay(await to_candid_HomeStay_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomeStay(await to_candid_HomeStay_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateHotel(arg0: Hotel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHotel(await to_candid_Hotel_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHotel(await to_candid_Hotel_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePartnerProfile(arg0: PartnerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePartnerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePartnerProfile(arg0);
            return result;
        }
    }
    async updatePartnerRoomDetails(arg0: PartnerRoomUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePartnerRoomDetails(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePartnerRoomDetails(arg0);
            return result;
        }
    }
}
function from_candid_AdminProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminProfile): AdminProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_HomeStay_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomeStay): Promise<HomeStay> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_Hotel_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Hotel): Promise<Hotel> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_RoomType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): RoomType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GuestProfile]): GuestProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HomeStay]): Promise<HomeStay | null> {
    return value.length === 0 ? null : await from_candid_HomeStay_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PartnerProfile]): PartnerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    adminKey: string;
    name: string;
    role: _UserRole;
    adminPassword: string;
}): {
    id: string;
    adminKey: string;
    name: string;
    role: UserRole;
    adminPassword: string;
} {
    return {
        id: value.id,
        adminKey: value.adminKey,
        name: value.name,
        role: from_candid_UserRole_n26(_uploadFile, _downloadFile, value.role),
        adminPassword: value.adminPassword
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    amenities: Array<string>;
    address: string;
    photos: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    name: string;
    description: string;
    amenities: Array<string>;
    address: string;
    photos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        amenities: value.amenities,
        address: value.address,
        photos: await from_candid_vec_n31(_uploadFile, _downloadFile, value.photos)
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    photoUrls: Array<string>;
    ownerMessage: string;
    ownerType: {
        admin: null;
    } | {
        partner: null;
    };
    partnerName: string;
    hotelId: string;
    ratings: Array<bigint>;
    description: string;
    amenities: Array<string>;
    googleMapsLink: [] | [string];
    videoUrls: Array<string>;
    partnerId: [] | [string];
    availability: boolean;
    price: bigint;
    roomType: _RoomType;
    distanceFromTemple: [] | [bigint];
    photos: Array<_ExternalBlob>;
    partnerPhoneNumber: string;
}): Promise<{
    id: string;
    photoUrls: Array<string>;
    ownerMessage: string;
    ownerType: Variant_admin_partner;
    partnerName: string;
    hotelId: string;
    ratings: Array<bigint>;
    description: string;
    amenities: Array<string>;
    googleMapsLink?: string;
    videoUrls: Array<string>;
    partnerId?: string;
    availability: boolean;
    price: bigint;
    roomType: RoomType;
    distanceFromTemple?: bigint;
    photos: Array<ExternalBlob>;
    partnerPhoneNumber: string;
}> {
    return {
        id: value.id,
        photoUrls: value.photoUrls,
        ownerMessage: value.ownerMessage,
        ownerType: from_candid_variant_n36(_uploadFile, _downloadFile, value.ownerType),
        partnerName: value.partnerName,
        hotelId: value.hotelId,
        ratings: value.ratings,
        description: value.description,
        amenities: value.amenities,
        googleMapsLink: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.googleMapsLink)),
        videoUrls: value.videoUrls,
        partnerId: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.partnerId)),
        availability: value.availability,
        price: value.price,
        roomType: from_candid_RoomType_n38(_uploadFile, _downloadFile, value.roomType),
        distanceFromTemple: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.distanceFromTemple)),
        photos: await from_candid_vec_n31(_uploadFile, _downloadFile, value.photos),
        partnerPhoneNumber: value.partnerPhoneNumber
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: _BookingStatus;
    userId: string;
    hotelId: string;
    checkInDate: _Time;
    guestInfo: _GuestProfile;
    bookingDate: _Time;
    checkOutDate: _Time;
    roomId: string;
    totalPrice: bigint;
}): {
    id: string;
    customerName: string;
    status: BookingStatus;
    userId: string;
    hotelId: string;
    checkInDate: Time;
    guestInfo: GuestProfile;
    bookingDate: Time;
    checkOutDate: Time;
    roomId: string;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_BookingStatus_n43(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        hotelId: value.hotelId,
        checkInDate: value.checkInDate,
        guestInfo: value.guestInfo,
        bookingDate: value.bookingDate,
        checkOutDate: value.checkOutDate,
        roomId: value.roomId,
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    notificationType: {
        profileUpdate: null;
    } | {
        booking: null;
    } | {
        newLogin: null;
    } | {
        partner: null;
    } | {
        payment: null;
    };
    unread: boolean;
    message: string;
    timestamp: _Time;
}): {
    id: string;
    notificationType: Variant_profileUpdate_booking_newLogin_partner_payment;
    unread: boolean;
    message: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        notificationType: from_candid_variant_n51(_uploadFile, _downloadFile, value.notificationType),
        unread: value.unread,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    partner: null;
}): Variant_admin_partner {
    return "admin" in value ? Variant_admin_partner.admin : "partner" in value ? Variant_admin_partner.partner : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    double: null;
} | {
    suite: null;
} | {
    single: null;
}): RoomType {
    return "double" in value ? RoomType.double : "suite" in value ? RoomType.suite : "single" in value ? RoomType.single : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    confirmed: null;
} | {
    pendingConfirmation: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "confirmed" in value ? BookingStatus.confirmed : "pendingConfirmation" in value ? BookingStatus.pendingConfirmation : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileUpdate: null;
} | {
    booking: null;
} | {
    newLogin: null;
} | {
    partner: null;
} | {
    payment: null;
}): Variant_profileUpdate_booking_newLogin_partner_payment {
    return "profileUpdate" in value ? Variant_profileUpdate_booking_newLogin_partner_payment.profileUpdate : "booking" in value ? Variant_profileUpdate_booking_newLogin_partner_payment.booking : "newLogin" in value ? Variant_profileUpdate_booking_newLogin_partner_payment.newLogin : "partner" in value ? Variant_profileUpdate_booking_newLogin_partner_payment.partner : "payment" in value ? Variant_profileUpdate_booking_newLogin_partner_payment.payment : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n55(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Hotel>): Promise<Array<Hotel>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Hotel_n29(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n32(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HomeStay>): Promise<Array<HomeStay>> {
    return await Promise.all(value.map(async (x)=>await from_candid_HomeStay_n34(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n49(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Booking_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Booking): _Booking {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_HomeStay_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomeStay): Promise<_HomeStay> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_Hotel_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Hotel): Promise<_Hotel> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_RoomType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): _RoomType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    amenities: Array<string>;
    address: string;
    photos: Array<ExternalBlob>;
}): Promise<{
    id: string;
    name: string;
    description: string;
    amenities: Array<string>;
    address: string;
    photos: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        amenities: value.amenities,
        address: value.address,
        photos: await to_candid_vec_n13(_uploadFile, _downloadFile, value.photos)
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: BookingStatus;
    userId: string;
    hotelId: string;
    checkInDate: Time;
    guestInfo: GuestProfile;
    bookingDate: Time;
    checkOutDate: Time;
    roomId: string;
    totalPrice: bigint;
}): {
    id: string;
    customerName: string;
    status: _BookingStatus;
    userId: string;
    hotelId: string;
    checkInDate: _Time;
    guestInfo: _GuestProfile;
    bookingDate: _Time;
    checkOutDate: _Time;
    roomId: string;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: to_candid_BookingStatus_n22(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        hotelId: value.hotelId,
        checkInDate: value.checkInDate,
        guestInfo: value.guestInfo,
        bookingDate: value.bookingDate,
        checkOutDate: value.checkOutDate,
        roomId: value.roomId,
        totalPrice: value.totalPrice
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    photoUrls: Array<string>;
    ownerMessage: string;
    ownerType: Variant_admin_partner;
    partnerName: string;
    hotelId: string;
    ratings: Array<bigint>;
    description: string;
    amenities: Array<string>;
    googleMapsLink?: string;
    videoUrls: Array<string>;
    partnerId?: string;
    availability: boolean;
    price: bigint;
    roomType: RoomType;
    distanceFromTemple?: bigint;
    photos: Array<ExternalBlob>;
    partnerPhoneNumber: string;
}): Promise<{
    id: string;
    photoUrls: Array<string>;
    ownerMessage: string;
    ownerType: {
        admin: null;
    } | {
        partner: null;
    };
    partnerName: string;
    hotelId: string;
    ratings: Array<bigint>;
    description: string;
    amenities: Array<string>;
    googleMapsLink: [] | [string];
    videoUrls: Array<string>;
    partnerId: [] | [string];
    availability: boolean;
    price: bigint;
    roomType: _RoomType;
    distanceFromTemple: [] | [bigint];
    photos: Array<_ExternalBlob>;
    partnerPhoneNumber: string;
}> {
    return {
        id: value.id,
        photoUrls: value.photoUrls,
        ownerMessage: value.ownerMessage,
        ownerType: to_candid_variant_n10(_uploadFile, _downloadFile, value.ownerType),
        partnerName: value.partnerName,
        hotelId: value.hotelId,
        ratings: value.ratings,
        description: value.description,
        amenities: value.amenities,
        googleMapsLink: value.googleMapsLink ? candid_some(value.googleMapsLink) : candid_none(),
        videoUrls: value.videoUrls,
        partnerId: value.partnerId ? candid_some(value.partnerId) : candid_none(),
        availability: value.availability,
        price: value.price,
        roomType: to_candid_RoomType_n11(_uploadFile, _downloadFile, value.roomType),
        distanceFromTemple: value.distanceFromTemple ? candid_some(value.distanceFromTemple) : candid_none(),
        photos: await to_candid_vec_n13(_uploadFile, _downloadFile, value.photos),
        partnerPhoneNumber: value.partnerPhoneNumber
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_admin_partner): {
    admin: null;
} | {
    partner: null;
} {
    return value == Variant_admin_partner.admin ? {
        admin: null
    } : value == Variant_admin_partner.partner ? {
        partner: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): {
    double: null;
} | {
    suite: null;
} | {
    single: null;
} {
    return value == RoomType.double ? {
        double_: null
    } : value == RoomType.suite ? {
        suite: null
    } : value == RoomType.single ? {
        single: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    confirmed: null;
} | {
    pendingConfirmation: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value == BookingStatus.pendingConfirmation ? {
        pendingConfirmation: null
    } : value;
}
async function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
